config/routes.rb
Tradaculator::Application.routes.draw do
  devise_for :users
  match 'gamers' => 'users#index', :via => :get, :as => 'users'
  match 'gamer/:username' => 'users#show', :via => :get, :as => 'user'
  
  resources :related_items
  
  match 'library' => 'library_items#index', :via => :get, :as => 'library_items'
  match 'library' => 'library_items#destroy', :via => :delete, :as => 'library_items'
  match 'library' => 'library_items#create', :via => :post, :as => 'library_items'
  match 'library-toggle' => 'library_items#toggle', :via => :get, :as => 'library_toggle'
  
  match 'page/:page' => 'trade_in_values#show', :as => 'trade_in_values_no_query'
  match 'search(/:query(/page/:page))' => 'trade_in_values#show', :as => 'trade_in_values'
  match 'game/:upc' => 'games#show', :as => 'game'

  root :to => 'trade_in_values#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :values, :dependent => :destroy
  has_many :library_items
  has_many :users, :through => :library_items

  validates_uniqueness_of :upc
  validates_presence_of :title
  validates_presence_of :platform
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :json, :js
  caches_action :show, :expires_in => 30.minutes, :cache_path => Proc.new { |c|
      "#{Rails.env} #{c.params} #{c.request.xml_http_request?}"
  }, :unless => Proc.new { |c|
    c.send(:current_user)
  }
  
  def show
    # expires_in 30.minutes, :public => true
    @game = Game.find_by_upc(params[:upc])
    @vendors = Vendor.all
    @top_value = @game.values.top_current_value

    # set up variables to track most recent value
    current_amazon_value = false
    current_best_buy_value = false
    current_glyde_value = false
    
    dataset_length = 150

    @amazon_values = []
    @game.values.where(:vendor=>'amazon').limit(dataset_length).each_with_index do |v,i|
      @amazon_values << "[#{v.created_at.to_f.to_i * 1000},#{v.value_as_decimal}]"
      current_amazon_value = v.value if i == 0 # first value is highest
    end

    @best_buy_values = []
    @game.values.where(:vendor=>'best_buy').limit(dataset_length).each_with_index do |v,i|
      @best_buy_values << "[#{v.created_at.to_f.to_i * 1000},#{v.value_as_decimal}]"
      current_best_buy_value = v.value if i == 0 # first value is highest
    end

    @glyde_values = []
    @game.values.where(:vendor=>'glyde').limit(dataset_length).each_with_index do |v,i|
      @glyde_values << "[#{v.created_at.to_f.to_i * 1000},#{v.value_as_decimal}]"
      current_glyde_value = v.value if i == 0 # first value is highest
    end
    
    #collect and sort values
    @top_values = {
      :amazon => current_amazon_value,
      :best_buy => current_best_buy_value,
      :glyde => current_glyde_value
    }.reject{ |vendor, value| value == false }.sort_by { |vendor, value| -value }
    
    if request.xhr?
      render "_shutter", :layout => false
      return
    else
      respond_with(@game)
    end
  end
end

app/helpers/game_helper.rb
module GameHelper
  def is_library_item?(game_id)
    !current_user.games.where(:id => game_id).empty?
  end
  
  def current_library_item
    current_user.library_items.where(:game_id => @game.id).first
  end
end

app/views/games/_game.html.haml
- values = Value.top_current_value_per_vendor(game)
.p>
  .pw
    .f
      %a.game-link{:href=>game_path(game.upc)}
        %span
          %img{:src=>game.image || image_path('image_not_available.gif')}
    %header
      %h1
        %a.game-link{:href=>game_path(game.upc)}
          = game.title
      %p= game.platform
      .pbw
        .b.split
          %a.vn{:href=> fill_in(Vendor.all[values[0]['vendor'].to_sym][:url], :id => eval("game.#{Vendor.all[values[0]['vendor'].to_sym][:permalink]}_id"))}
            Trade It In
          %a.tv
            = currency values[0]['value']
        %ul.dd
          - values.each do |value|
            %li
              %a{:href=> fill_in(Vendor.all[value['vendor'].to_sym][:url], :id => eval("game.#{Vendor.all[value['vendor'].to_sym][:permalink]}_id"))}
                = value[:vendor].to_s.gsub('_',' ')
                %span
                  = currency value[:value]

app/views/games/_shutter.html.haml
#shutter
  #arrow
  .column-primary
    #graph
      :javascript
        var amazon = [#{@amazon_values.join(',')}];
        var best_buy = [#{@best_buy_values.join(',')}];
        var glyde = [#{@glyde_values.join(',')}];
                  
    %ul.side-by-side
      - @top_values.each do |top_value|
        %li
          .pbw
            .b
              - url = fill_in(@vendors[top_value[0].to_sym][:url], :id => eval("@game.#{@vendors[top_value[0].to_sym][:permalink]}_id"))
              %a.vn{:href=> url }
                = @vendors[top_value[0].to_sym][:name]
              %a.tv{:href=> url }
                = currency top_value[1]
          .description
            = @vendors[top_value[0].to_sym][:conditions]
            
  .column-secondary
    %ul.tool-list
      - if current_user && is_library_item?(@game.id)
        %li.library-item.library-toggle
          %a.current-user-library{:href => library_toggle_path(:game_id => @game.id), :title => "Remove from library", :rel => "nofollow"}
            You own this!
      - elsif current_user
        %li.library-item.library-toggle
          %a{:href => library_toggle_path(:game_id => @game.id), :rel => "nofollow"}
            Add to game library
      - else
        %li.library-item
          %a.sign-in-required{:href => library_toggle_path(:game_id => @game.id), :rel => "nofollow"}
            Add to game library
      %li.share
        - share_message = "Trade%20in%20#{@game.title}%20for%20up%20to%20#{currency @top_value.value}%20from%20#{@top_value.vendor.humanize}"
        %a{:href=>"#share"}
          Share trade-in values
        %ul
          %li
            %a{:href=>"mailto:?body=#{share_message}%20#{CGI::escape game_url(@game.upc)}"}
              Email
          %li
            %a{:href=>"https://twitter.com/share?url=#{CGI::escape game_url(@game.upc)}&text=#{share_message}&via=tradaculator", :class=>"popup"}
              Twitter
          %li
            %a{:href=>"https://www.facebook.com/sharer.php?u=#{CGI::escape game_url(@game.upc)}&t=#{share_message}", :class=>"popup"}
              Facebook
      -#%li
        -#%a{:href=>"#"}
          -#Set price alert

app/views/games/show.html.haml
.p>
  .pw
    .f
      %img{:src => @game.image || image_path('image_not_available.gif')}
    %header
      %h1= @game.title
      %p= @game.platform
      
= render :partial => "shutter"

- content_for :title do
  Get up to #{currency @top_value.value} for trade-in of #{@game.title} on #{@game.platform} from #{@top_value.vendor.humanize}